packages:
  - 'lix/packages/*'
  - '!lix/packages/exp'
  - 'inlang/source-code/*'
  - 'inlang/source-code/cross-sell/*'
  - 'inlang/source-code/plugins/*'
  - 'inlang/source-code/paraglide/*'
  - 'inlang/source-code/paraglide/paraglide-js-adapter-vite/tests/*'
  - 'inlang/source-code/paraglide/*/example'
  - 'inlang/source-code/paraglide/paraglide-js-adapter-next/examples/*'
  - 'inlang/source-code/templates/*'
  - 'inlang/source-code/message-lint-rules/*'
  - 'inlang/source-code/versioned-interfaces/*'
  - 'inlang/source-code/sdk/load-test'