name: Continuous Integration

on:
  pull_request:
    branches:
      - "main"

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"

      - name: remove cache folder on windows
        if: matrix.os == 'windows-latest'
        run: Remove-Item C:\npm\cache\* -Recurse -Force || true

      - name: Install dependencies
        run: npm ci

      - run: npm run lint

      - run: npm run build

      - run: npm run test

