name: Ninja i18n action

on: pull_request_target

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  pull-requests: write # Necessary to comment on PRs
  issues: read         # Necessary to read issue comments
  contents: read       # Necessary to access the repo content

jobs:
  ninja-i18n:
    name: Ninja i18n - Test NINJA-28
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout target
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: testing

      - name: Run Ninja i18n
        # @main ensures that the latest version of the action is used
        uses: ./testing/inlang/source-code/github-lint-action/internal-testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
