name: Links (Fail Fast)

on:
    push:
        branches:
          - "main"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Markdown files
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
          args: --verbose --no-progress './*/documentation/**/*.md' './*/documentation/**/**/*.md' './*/guides/**/*.md' './*/blog/**/*.md' './README.md' './*/README.md'
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
