name: Publish @inlang/ide-extension to VSCode Marketplace

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ci-cd
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Build VSCode extension package
        run: npm run package -w source-code/ide-extension
      - name: Publish to VSCode Marketplace
        run: npx vsce publish -p ${{secrets.VSCODE_MARKETPLACE_TOKEN}}
        working-directory: ./source-code/ide-extension
        env:
          VSCE_TOKEN: ${{secrets.VSCODE_MARKETPLACE_TOKEN}}
