name: Publish @inlang/core to NPM

on:
  push:
    paths:
      - "source-code/core/**"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ci-cd
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: npm run test -w @inlang/core
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: source-code/core/package.json
