name: Publish @inlang-git/fs to NPM

on:
  # manually triggering the workflow if desired
  workflow_dispatch:

  push:
    paths:
      - "source-code-git/fs/**"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ci-cd
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: npm run test -w @inlang-git/fs
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: source-code-git/fs/package.json
