name: Publish plugins/*

on:
  # manually triggering the workflow if desired
  workflow_dispatch:

  push:
    paths:
      - "source-code/plugins/*/package.json"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ci-cd
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install

      - run: npm run build
      - run: npm run test

      # all plugins are published from the same workflow
      # npm-publish will only publish the package if it has changed

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: source-code/plugins/standard-lint-rules/package.json

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: source-code/plugins/i18next/package.json

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: source-code/plugins/json/package.json
