name: Publish @inlang/sdk-js-plugin to NPM

on:
  # manually triggering the workflow if desired
  workflow_dispatch:

  push:
    paths:
      - "source-code/sdk-js-plugin/package.json"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ci-cd
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Doppler CLI for (public) env variables
        uses: dopplerhq/cli-action@v2

      - run: npm install

      - name: build
        run: doppler run -- node_modules/.bin/turbo run build --filter @inlang/sdk-js-plugin
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PRODUCTION_ENV_TOKEN }}

      - run: node_modules/.bin/turbo run test --filter @inlang/sdk-js-plugin
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: source-code/sdk-js-plugin/package.json
