name: Test

on:
  pull_request:
    branches:
      - "main"

  push:
    branches:
      - "main"

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      # --------- START SETUP OF REPOSITORY ---------
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci
      # --------- END SETUP OF REPOSITORY ---------

      - run: npm run test
      - run: npm run lint
      - run: npm run build
