name: Test Code

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install --no-save

      - name: run build
        run: npm run build

      - name: Run all tests
        if: startsWith(matrix.os, 'windows') == false
        run: npm run test

      - name: Run tests relevant to the Windows platform
        if: startsWith(matrix.os, 'windows')
        run: npm run test:windows
