name: Test

on:
  pull_request:
    branches:
      - "main"

  push:
    branches:
      - "main"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # not using checkout because we need to persist the repo for the next jobs
      - name: Clone repository and install dependencies
        run: |
          git clone https://github.com/inlang/inlang.git &&
          cd inlang && 
          npm ci

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
