name: Test

on:
  pull_request:
    branches:
      - "main"

  push:
    branches:
      - "main"

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      # not using checkout because we need to persist the repo for the next jobs
      - name: Clone repository
        run: |
          git clone https://github.com/inlang/inlang.git
          cd inlang

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # use lock file to install dependencies (faster)
      - run: npm ci

  lint:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  test:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

  build:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
