# see https://github.com/changesets/action#without-publishing

name: versioning

on:
  # trigger this workflow when the CI workflow is completed
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types: 
      - completed
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  versioning:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Doppler CLI for env (public) variables
        uses: dopplerhq/cli-action@v2

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
